GET http://localhost:8000/member/member/count
Accept: application/json

###


POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=1234677


###

POST http://localhost:8000/member/member/sendCode
Content-Type: application/x-www-form-urlencoded

mobile=12399890987

###

POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile=12399890987&code=7777